# Generated by Django 2.0.4 on 2018-04-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('car_price', models.BigIntegerField()),
                ('car_brand', models.CharField(max_length=100)),
                ('car_horsepower', models.CharField(max_length=50)),
                ('car_mileage', models.TextField()),
            ],
        ),
    ]
