# Generated by Django 2.0.4 on 2018-04-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelforms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_brand',
        ),
    ]
