# Generated by Django 2.0.4 on 2018-04-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelforms', '0002_remove_car_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_mileage',
            field=models.TextField(verbose_name=2),
        ),
    ]
