# Generated by Django 2.0.4 on 2018-04-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelforms', '0003_auto_20180428_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_mileage',
            field=models.TextField(),
        ),
    ]
