# Generated by Django 2.0.4 on 2018-04-28 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelforms', '0006_car_car_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_choices',
            new_name='radio',
        ),
    ]
