# Generated by Django 2.0.4 on 2018-04-28 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelforms', '0007_auto_20180428_0652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='radio',
            new_name='car_fueltype',
        ),
    ]
