# Generated by Django 2.0.4 on 2018-04-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelforms', '0008_auto_20180428_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_geartype',
            field=models.CharField(default='', max_length=250, verbose_name='Selected your choice'),
            preserve_default=False,
        ),
    ]
