# Generated by Django 2.0.4 on 2018-04-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelforms', '0009_car_car_geartype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_geartype',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=1, verbose_name='Selected your choice'),
        ),
    ]
