# Generated by Django 2.0.4 on 2018-04-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelforms', '0010_auto_20180428_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_brand',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
