# Generated by Django 2.0.4 on 2018-04-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelforms', '0011_car_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_fueltype',
            field=models.CharField(choices=[('petrol', 'petrol'), ('diesel', 'diesel')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_geartype',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=10, verbose_name='Selected your choice'),
        ),
    ]
