# Generated by Django 2.0.4 on 2018-04-28 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelforms', '0013_auto_20180428_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_mileage',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(5)]),
        ),
    ]
